### ISSUE TITLE
Добавление изменений пропуска

### ISSUE THREAD

**Issue by Pro100CaHya** [DmitryGolubenkov/BusinessCenterACS#20]
Основная ветка: `feature/frontend`
Необходимо реализовать редактирование изменений выбранного пропуска.
Создал отдельную страницу для редактирования
Но есть проблема - необходимо как-то передать параметры пропуска с одной страницы (со страницы списка пропусков) на другую
Страница списка пропусков выглядит следующим образом:
![image](https://user-images.githubusercontent.com/47455676/143779052-a041bff6-33c9-42c0-957c-1e553953ae6e.png)
При нажатии на кнопку редактирования загружается страница:
![image](https://user-images.githubusercontent.com/47455676/143779077-cfe773ac-b0d4-4bee-aa76-86ab126be32d.png)
В поля GUID пропуска, даты начала и окончания, статуса необходимо как-то передать информацию со страницы списка на страницу редактирования
- [x] Настроить передачу параметров пропуска
- [x] Настроить сам процесс редактирования (взаимодействие с Web API)

**Comment by DmitryGolubenkov** [comment]
Требуется для #11
